### ISSUE TITLE
SPARC - Receive pKa and pKb separately

### ISSUE THREAD

**Issue by popenc** [quanted/cts_app#105]
Would be nice to get explicit pKb values along with pKa from SPARC. Below is the current way SPARC is called from CTS, which seems to return pKa and pKb all with the same label of "pKa." (I'm not a chemist).

URL: /sparc-integration/rest/calc/fullSpeciation

POST example:

{
            "type":"FULL_SPECIATION",
            "temperature":25.0,
            "minPh":0,
            "phIncrement":0.5,
            "smiles": "CCCC",
            "username":"browser1",
            "elimAcid":[],
            "elimBase":[],
            "considerMethylAsAcid": True
        }

**Comment by koopmans-michaela** [comment]
Read macroPkaType: "Acid" or "Base" to determine if a pKa or pKb. If "Both", call it a pKa. Drop the "out of range" notice for SPARC, and only list "none" in the pKa box if absolutely nothing comes back in range from the calculator.

**Comment by koopmans-michaela** [comment]
I've tested a couple chemicals that I was concerned about, but it looks like this fix should work. I've attached some example chemicals.

[SPARC WS pKa-pKb examples.docx](https://github.com/quanted/cts_app/files/1528891/SPARC.WS.pKa-pKb.examples.docx)
