### ISSUE TITLE
File download buttons easier to locate

### ISSUE THREAD

**Issue by popenc** [quanted/cts_app#109]
The idea is to put the file download buttons in a place that's easy to find, like at the "Calculate" button of the p-chem table.

**Comment by popenc** [comment]
@koopmans-michaela @cstevens227 Before I dive into this change I'd like to get a little more info about how this would look. It's probably easiest if I go through some ideas by workflow and mode, so here we go.



> **Speciation workflow output (single):** The only change for this, I'm guessing, is to not add anymore file download buttons. I'd like to at least move the file download buttons below the output page title, which is an issue for all the output pages since the upgrade from the old look to the new EPA look a while back.
> 
> **Speciation workflow output (batch):** How about for this output page, the download buttons can be moved below the title like the previous workflow, and the popup message can be removed. Also, perhaps the message about the CSV download button could be in red to make it easier to see?
> 
> **Physicochemical workflow output (single):** Once again, move buttons at top below the title. Is this where it would make sense to put additional download buttons below the "Calculate" button on the p-chem table?
> 
> **Physicochemical workflow output (batch):** Needs CSV button below the title, and like chemspec batch it probably doesn't need the popup message, which I'm thinking was originally intended just for pchem downloads on gentrans single mode output. Red font for "Batch results ready for download".
> 
> **Transformation products output (single):** Buttons below title. This is where the popup message to download a file at the top of page makes sense. Additional download buttons could be added below the "Calculate" button of the p-chem table here. Is this the only place that makes sense for the extra buttons to go? 
> 
> **Transformation products output (batch):** Same changes as the other two batch modes.




If there's a popup message telling the user the download buttons are at the top of the page after p-chem data is collected, then do we really need to add additional download buttons in the p-chem table?

If we do add the extra download buttons, then does it make sense to still have the popup message about going to the top of the page?

Also, I think it's worth considering an increase in trigger happiness when it comes to downloading files if we add the extra buttons. Just something to think about.

**Comment by koopmans-michaela** [comment]
I think we're pretty much on the same page. Here are my thoughts.

**Speciation single:** Just move the download buttons to below the page title. That should be enough.

**Speciation batch:** Pretty much like you said - move the button below the title, take out the popup message. Changing the font color might help, we can see how it looks.

**Physicochemical single:** Move buttons to below title. I think this is indeed the place it would make the most sense to have a second download button near the "Calculate" button, but that should be sufficient.

**Physicochemical batch:** Same as speciation, move the button below the title and take out the popup message. Try out the red font. You're right that the popup message is really only helpful for the pchem downloads in the gentrans output.

**Transformation single:** This seems to be the most involved workflow. Buttons below the title. Probably good to have the popup message to distinguish that output being ready from the original output loading. If we do go with an extra download button, maybe have the popup say something like "results available for download below table or at top of page". I'm not convinced that we need a second download button here if we have a popup, in regards to your questions. @cstevens227 Do you have thoughts on this?

**Transformation batch:** Same as the other batch modes.

You have a good point about the trigger happiness for the downloads. One thing I've noticed is that I can't download the output file in the same file type more than once (as far as I can tell, I always get an error) without running the workflow again. If we don't want people to be hitting the download buttons over and over, we could just make that into an official error message. On the other hand, I am prone to hitting download and losing track of the files, but hopefully that won't be a big issue for our users.

**Comment by koopmans-michaela** [comment]
So far, I've talked with Caroline and Eric briefly about the fixed download buttons and they seemed to like it. Seems like this would solve having extra download buttons - just stick with the fixed buttons on the "single" output pages (no additional buttons) and only have a popup message alerting the user that pchem prop download is available at the top right in the single transformation workflow.

**Comment by popenc** [comment]
I'm thinking this issue is resolved. Feel free to reopen if not.

And in regards to this issue, I kept the "top-right" wording because the floating download buttons solution keeps them in the top-right corner. Hope that's good for everyone!
