### ISSUE TITLE
Upload new PDF of hydrolysis library to server

### ISSUE THREAD

**Issue by popenc** [quanted/cts_app#110]

**Comment by popenc** [comment]
Alrighty, so the updated PDF is on the internal server. The links are working for me when I test them locally in chrome and firefox, but am still waiting to hear back from the call center in regards to accessing the internal network again, so I can't test them there.

Given that the update has the same name as before and is referencing a large, static file. I think the browser caching problems we run into will occur, so if possible try clearing all cache and testing on a few browsers if it seems like CTS is still referencing the old one.

I'm going to go ahead and close it here.

**Comment by koopmans-michaela** [comment]
Links are working for me in Chrome, even without clearing the cache. I'll check back in the future to see if the caching issue comes back up.
