### ISSUE TITLE
Physicochemical Properties Workflow Description Edit

### ISSUE THREAD

**Issue by koopmans-michaela** [quanted/cts_app#113]
On the internal server's CTS homepage (https://qedinternal.epa.gov/cts/), it looks like the text for the Calculate Physicochemical Properties Workflow description was copied over incorrectly. None of the text updates for those descriptions are on the public server yet, so it's only an issue on the internal page right now. Please update the description to the following text:

Calculate Physicochemical Properties Workflow: Uses CTS’s Chemical Editor (CE) and the Physicochemical Properties Calculator (PCP) Module. The PCP Module uses four stand-alone calculators (EPI Suite, SPARC, ChemAxon, and TEST) to find physicochemical properties for the entered chemical.

**Comment by popenc** [comment]
I'll take a look at it and let you know when it's updated.

**Comment by popenc** [comment]
@koopmans-michaela Okie doke, the above text has been changed on the internal server, and the other two cosmetic issues as well: link to Plugin Calculators and removed CompTox link.
