### ISSUE TITLE
Production/Accumulation Document

### ISSUE THREAD

**Issue by popenc** [quanted/cts_app#145]
Write explanation document for site about production/accumulation values in the transformation output. Add in likelihood thresholds/explanations. Add in explanation of why global accumulation numbers change depending on number of generations called. (RG: currently without document as of 9/10/2020)

**Comment by cstevens227** [comment]
Question Submitted on "Contact Us" page: 2021-11-01 14:54:46
"I have been working with the CTS Generate Transformation Products workflow, as well as T.E.S.T. and am wondering what exactly the accumulation and global accumulation scores describe. In the user's guide, it says this is described in other documentation, but I haven't been able to find any on the webpage."
CS responded to submitter on 11/12/2021 with draft documentation on the Metabolizer algorithm.

**Comment by popenc** [comment]
Documentation was uploaded to GDIT dev last week and the reaction example image has been fixed.

**Comment by popenc** [comment]
I'm pretty sure this has been on the prod server for a while, just haven't closed it.
