### ISSUE TITLE
Images not showing up in pdf output for Transformation Products workflow

### ISSUE THREAD

**Issue by cstevens227** [quanted/cts_app#160]
Instead of showing an image, the pdf shows the following, as an example:
<img class="metabolite" id="molecule 1"alt="ClCCOP(=O)(OCCCl)OCCCl"
src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAPoAAAEiCAYAAADQ9s/LAAAQnElEQVR42u2db2id1RnAn7LUpdJCGP2QYdyCCy7DsGVbmP3Q2UDEKmXUEUuEfsgg1spKW6RjVQJNoR86V7CwomkSJR+height=290 />

This is happening on https://qed.epa.gov/cts/ as well as the GDIT development server.

**Comment by popenc** [comment]
Thanks for making this an issue in GitHub!

Do you know if there's a server that the PDFs are showing up as expected?

**Comment by popenc** [comment]
This is happening on GDIT staging and CDX server as well, and the HTML files are also affected.

Pushed a commit up (780ae75b01b08cc5977c6570b51e226de28e1ce1) that should fix this issue.

TODO: Security scan(s) to ensure this change doesn't create a security risk.

**Comment by popenc** [comment]
This now works in production.
