### ISSUE TITLE
Disable batch ChemAxon property and pKa calculations

### ISSUE THREAD

**Issue by cstevens227** [quanted/cts_app#203]
To comply with request by Richard Johnson, please disable the batch functionality for getting calculated physicochemical properties and pKa values from ChemAxon.

**Comment by popenc** [comment]
NOTE: SSL certs for qedlinux1stg (EPA staging) are currently expired and need to be renewed before being able to access the page  for testing.

**Comment by popenc** [comment]
This is now on qed.epa.gov. Bumped version to v1.3.1 to more easily track updates.
