### ISSUE TITLE
EPI KOC values of 10.00

### ISSUE THREAD

**Issue by popenc** [quanted/cts_app#35]
Issue or moreso a question relating to EPI refactor issue #31 

Often I find that EPI Suite returns a value of 10.00 for KOC. Should this be validating at the CTS backend and return a message to the user in the table cell instead of 10.00?

**Comment by koopmans-michaela** [comment]
That is strange, I haven't seen that issue with my test molecules. Could you give an example and I'll look into it?

**Comment by popenc** [comment]
When I try "aspirin" I get a KOC of 10.00. To me it looks like a possible error value like TEST's -9999.

**Comment by koopmans-michaela** [comment]
Oddly enough, the one for aspirin looks right from the desktop application. Those kinds of errors do show up and are hard to distinguish, though, so if you find more let me know and I'll take a look at those, too.

**Comment by popenc** [comment]
I'm going to close this issue for now, but reopen it if I run into this value for other chemicals.
