### ISSUE TITLE
Various Pchem Calculator API Errors

### ISSUE THREAD

**Issue by koopmans-michaela** [quanted/cts_app#53]
I'm seeing some new API errors popping up where molecules don't work.

EPI Suite:

-For a few molecules, a Gateway Time-out error has come up. (Example is dinotefuran, SMILES: [O-][N+](=O)N=C1NCCN1CC1=CN=C(Cl)C=C1) I'm guessing this relates to what you've been working on with timing out, but I thought I'd mention it.
![api-epi-error-chrome](https://cloud.githubusercontent.com/assets/26609201/25862806/581e22d8-34b7-11e7-9474-2668606eb89e.PNG)

-I tried to verify that the calculator-specific SMILES filter is working in APIs, and it looks like it does for most molecules. For cyhalothrin, if  I input the un-standardized SMILES, it tells me that the system can't filter the SMILES string for EPI data. If  I standardize the SMILES myself, it works. I haven't seen this for other molecules that go through SMILES filtering though.
Cyhalothrin SMILES un-standardized: CC1(C)[C@@H](\C=C(/Cl)C(F)(F)F)[C@H]1C(=O)O[C@H](C#N)C1=CC=CC(OC2=CC=CC=C2)=C1
Cyhalothrin SMILES standardized: CC1(C)C(C=C(Cl)C(F)(F)F)C1C(=O)OC(C#N)c1cccc(Oc2ccccc2)c1
![api-epi-cyhalothrin-smilesfilter-error](https://cloud.githubusercontent.com/assets/26609201/25862804/57e0bde4-34b7-11e7-9ed2-f223f9d3d38d.PNG)

SPARC:

-For cyhalothrin again, I get an error saying "This QueryDict instance is immutable". No error if I use the standardized SMILES though. Possibly another SMILES filtering error? Odd, though, since neither of these SMILES errors show up in CTS as far as I can tell. I've had some issues with cyhalothrin having errors in the CTS testing values, so it may just be the molecule or there may be something going on with the communication from SMILES processing to calculator.
![api-sparc-cyhalothrin-immutable-error](https://cloud.githubusercontent.com/assets/26609201/25862805/57e45742-34b7-11e7-9ec7-471deebc1bcd.PNG)

**Comment by koopmans-michaela** [comment]
Slight correction: I am verifying the SMILES filtering for the APIs and it looks like it works for most molecules in SPARC, however EPI is giving me time-out errors so I haven't verified that processing yet. Before, it looked like most molecules besides cyhalothrin were working with the processing, but I want to double-check that once EPI is working again.

**Comment by popenc** [comment]
Seems like something up with the EPI Suite server if I had to guess. When logged into server 1, the following request to EPI was tested (same as API docs example request):

` curl -X POST -H "Content-Type: application/json" -d '{"structure": "CCC"}' http://172.20.100.18/episuiteapi/rest/episuite/waterSolubility/estimated`

The following message is returned from the EPI Suite server:

`"Error calculating Water Sol (mg/L)(estimated) with argument CCC ."`

**Comment by popenc** [comment]
I'm assuming from our meeting yesterday that this issue can be closed.

**Comment by koopmans-michaela** [comment]
After verification today:

1. The first error of Gateway timeouts is still coming up.

2. While I did copy the wrong SMILES into the GitHub issue for the second error, I copied the correct SMILES into the API where I was testing it and it is still giving me the same issue. I'm wondering if it's because of the "/" characters, so I will try some other molecules with "/"s, however the SMILES works fine in CTS.

**Comment by popenc** [comment]
For the timeout issue, if you change the POST from
```
{
  "chemical": "[O-][N+](=O)N=C1NCCN1CC1=CN=C(Cl)C=C1",
  **"calc": "string"**,
  "prop": "water_sol"
}
```

To
```
{
  "chemical": "[O-][N+](=O)N=C1NCCN1CC1=CN=C(Cl)C=C1",
  **"calc": "epi",**
  "prop": "water_sol"
}
```

**Comment by koopmans-michaela** [comment]
Okay, thanks. What is the difference/should the calc value always be 'string'/is there a way that I can tell which one to use?

**Comment by popenc** [comment]
It should always be the name of the calc, and all the endpoints do that except for EPI. I've changed that locally and just have to put it on the server, but that takes time as we have a QA process for that.

So until the server update, the EPI /run endpoint needs the 'calc' changed to 'epi' because the SMILES filter looks for that value to determine how to filter. Since 'calc' was 'string', it never got filtered for EPI and timed out when requesting data from the EPI server.

**Comment by koopmans-michaela** [comment]
Ahh, sounds good. I will change it when I make requests to EPI.

**Comment by popenc** [comment]
The 'calc' key for /epi/run endpoint should have 'epi' now, so that issue should at least be resolved. I'm messing around with CC1(C)C(\C=C(/Cl)C(F)(F)F)C1C(=O)OC(C#N)C1=CC=CC(OC2=CC=CC=C2)=C1 now and yeah it's working fine on the CTS frontend. At the moment I'm thinking that you're right and that the "/" (probably the "\" in this case) is messing up the request in the API docs; the error looks to be on the API docs level. Shouldn't be too hard to resolve.

**Comment by popenc** [comment]
Upon further investigation, the backslash, "\" is prematurely escaping the chemical string, so when it gets to the CTS backend, the chemical value is blank. Testing the same chemical using "Cyhalothrin" works fine. I'm going to look into whether this happens on the API docs library, or if it's something we can adjust on the CTS side (the latter is ideal, as modifying a pre-existing library wouldn't be very sustainable).

**Comment by popenc** [comment]
Haha the backslash didn't show up due to encoding, which is coincidentally the problem the comment's about. Will this work? backslash: "\\"

**Comment by koopmans-michaela** [comment]
Oh good, I was trying to figure that one out! Hopefully this can be fixed on the CTS side.

**Comment by popenc** [comment]
Closing this issue and opening new one that's specifically the backslash problem
