### ISSUE TITLE
CTS: Metabolizer Library Versions for Reduction & Hydrolysis?

### ISSUE THREAD

**Issue by koopmans-michaela** [quanted/cts_app#55]
I just wanted to double check what library versions are being used in CTS currently for Reduction & Hydrolysis in the transformation pathway? I am verifying the issues seen with progeny in CTS when these libraries are combined vs. the desktop output.

The latest version of the hydrolysis library (1.7) should be coming your way soon. Please let me know once this has been updated so that I can validate any further issues correctly on the desktop.

**Comment by popenc** [comment]
@kurtw555  I'm pretty sure the libraries being used on the server are 1.6 for abiotic hydrolysis, and 1.4 for abiotic reduction.
