### ISSUE TITLE
Dockerize CTS

### ISSUE THREAD

**Issue by kurtw555** [quanted/cts_app#6]
Containerize CTS with Docker, encapsulating the django, redis, nodejs, etc. that's used in CTS.

**Comment by popenc** [comment]
Current issue with CTS dockerization, nickp branch version 1.7.2: Celery container not connecting to redis container. REDIS_HOSTNAME set to "redis," but celery container still trying to connect to localhost instead.

**docker-compose.yml**:

> version: '2'
 volumes:
  collected_static: {}
 services:
  # CTS Django front-end
  cts_django:
    image: cts-uwsgi-django:latest  # built image for cts-uwsgi-django
    expose:
    - "8080"
    volumes:
    - collected_static:/src/collected_static
    environment:
    - REDIS_HOSTNAME="redis"  # Set Redis hostname as ENV (value same as 'redis:redis' in links)
    links:
    - redis
    - worker_chemaxon:worker_chemaxon

  # # Redis (message broker)
  redis:
    image: redis:latest
    hostname: redis
    # expose:
    # - "6379"
    ports:
    - "6379:6379"

  # NGINX web server
  nginx:
    image: popenc/cts-nginx:stable
    ports:
    - "80:80"
    - "443:443"
    links: 
    - cts_django:uwsgi
    volumes_from:
    - cts_django:ro

  # # Celery worker - ChemAxon calc
  worker_chemaxon:
    image: cts-uwsgi-django:latest
    command: celery worker -A celery_cts -Q chemaxon -l info -n chemaxon_worker -c 2
    links:
    - redis
    environment:
    - REDIS_HOSTNAME="redis"

**Log**:
### > [33mworker_chemaxon_1  |[0m [2016-12-05 08:44:58,044: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: .
> [33mworker_chemaxon_1  |[0m Trying again in 4.00 seconds...
> [33mworker_chemaxon_1  |[0m
> [33mworker_chemaxon_1  |[0m [2016-12-05 08:45:02,053: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: .
> [33mworker_chemaxon_1  |[0m Trying again in 6.00 seconds...
> [33mworker_chemaxon_1  |[0m
> [33mworker_chemaxon_1  |[0m [2016-12-05 08:45:08,064: ERROR/MainProcess] consumer: Cannot connect to redis://localhost:6379/0: .
> [33mworker_chemaxon_1  |[0m Trying again in 8.00 seconds...
> [33mworker_chemaxon_1  |[0m
