### ISSUE TITLE
Measured returning "Input string was not in a correct format" for CC(O)CCO 

### ISSUE THREAD

**Issue by popenc** [quanted/cts_app#62]
pchem request for CC(O)CCO with Measured calculator is returning following error to CTS backend:

![image](https://user-images.githubusercontent.com/7785228/26953144-aee0967e-4c76-11e7-89b7-85472255dae2.png)

**Comment by popenc** [comment]
This is also causing the issue with /cts/testing/ CSV not being created.

**Comment by popenc** [comment]
@koopmans-michaela @kurtw555 It seems like there's a discrepancy between Measured on the desktop versus the web services for the SMILES CC(O)CCO.

I've directly tested the p-chem request to Measured directly using [postman](https://www.getpostman.com/apps) and the following is returned from Measured web services: 

> Input string was not in a correct format.

Doesn't seem like an encoding issue after testing directly with postman. If anything, a cleaner response needs to happen for Measured if it encounters this problem instead of returning "null," which is causing the /cts/testing/ issue of not returning an output CSV.

**Comment by popenc** [comment]
@koopmans-michaela Is Measured web services returning "input string was not in a correct format" for CC(O)CCO an issue to look into, or can it be closed now that it's returning something (albeit a message instead of data)?

**Comment by koopmans-michaela** [comment]
It can probably be closed but I'll put the input string thing as a backburner issue because I want to know if it's something we can fix or not, or if it will come up again.
