### ISSUE TITLE
Output CSV sometimes not downloading, especially with Measured requests

### ISSUE THREAD

**Issue by popenc** [quanted/cts_app#68]
@koopmans-michaela  Is this still happening for you sometimes? I haven't been able to trigger this issue since updating the server yesterday with Measured returning a message for CC(O)CCO (as opposed to returning nothing at all, which was causing problems)

**Comment by koopmans-michaela** [comment]
The Measured csv is now downloading, but it only shows a list of SMILES strings with no data.
