### ISSUE TITLE
Execute stress tests

### ISSUE THREAD

**Issue by kurtw555** [quanted/cts_app#7]
It'll be refreshing to have some legitimate stress testing results for CTS, testing common user patterns with multiple users at a time. A report of some results for Wednesday is the aim.

**Comment by popenc** [comment]
popenc/cts_stress is working now and has been used to stress test the current CTS deployment, but further stress tests need to be performed as we migrate to django channels and experiment with retry/validation logic and handling various concurrences across calculator workers (e.g., ChemAxon can handle a few calls in parallel whereas TEST and most others cannot).

**Comment by popenc** [comment]
Closing this until stress tests are performed again, which should be after the calcs refactor with retries and data validation.
