### ISSUE TITLE
Finish exception handling for ACTORWS in Chemical Editor

### ISSUE THREAD

**Issue by popenc** [quanted/cts_app#92]
Currently, if actorws doesn't have any data, CTS is returning an error message to the user at the Chemical Editor tab. The expected behavior is that CTS just uses the chemaxon chemical information if data from actorws is not available.

**Comment by popenc** [comment]
I dove into this yesterday and tested the two chemicals that don't have ACTORWS results:

- 2,5-dibromodiphenylether -- This returns "Cannot read molecule file" as an error message from jchem web services, so that's why it's returning an error.

- 2,5-dibromophenoxybenzene -- This works.

- 3315-66-3 -- This returns an error from jchem web services as well: "CAS number cannot be converted."

- BrC1=CC(OC2=CC=CC=C2)=C(Br)C=C1 -- This works.

And here are the results from the 2nd chemical with no ACTORWS results:

- 1,6-dichlorodibenzodioxin -- This returns a jchem ws error.

- 1,6-dichlorooxanthrene -- This works.

- 38178-38-0 -- This works (jchem ws recognizes it).

- ClC1=C2OC3=CC=CC(Cl)=C3OC2=CC=C1 -- This works as well.

I figured I'd reopen this issue for easier visibility, but close it if this is ok. Seems like it's only certain forms that aren't working, and they're not working because Jchem web services are returning an error.

**Comment by koopmans-michaela** [comment]
Looks like this is fixed with the "Name not recognized" error message.
