### ISSUE TITLE
Hexachloroethane product [H][C]([H])(Cl)=O returns "Inconsistent molecular structure" from Jchem WS

### ISSUE THREAD

**Issue by popenc** [quanted/cts_app#97]
When performing a transformation request for hexachloroethane, mammalian metabolizer, 4 generations, I noticed that the above product hangs up the entire chem info request process.

After looking into the logs, it appears that the request to jchem for major tautomer for the above product is returning the following result:

{'headers': {'error': {'name': 'error', 'type': 'TEXT', 'source': 'CALCULATOR'}}, 'error': 'Inconsistent molecular structure.'}

This kills the CTS.

**Comment by popenc** [comment]
@koopmans-michaela Has this ever been a problem before? I can't recall this workflow setup failing in the past. Nevertheless, I've added a check that skips the major tautomer step if it returns an error, and goes onto the next step in the SMILES filtering.

This could relate to SMILES filtering issues. I'll document some request and logs that show the filtering process.

**Comment by koopmans-michaela** [comment]
@popenc I don't remember this being an issue, though I don't usually run hexachloroethane with the mammalian library. It doesn't look like a valid SMILES string to me, but I see it in the Metabolizer desktop results, so apparently it's valid enough for that. Just so I'm clear, is it getting the major tautomer as part of the pchem properties request for the products? I'm looking into if it standardizes/tautomerizes correctly on the desktop.

**Comment by popenc** [comment]
Here's an overview of the transformation workflow from transformation request to products showing up on the tree:

When the user makes a "submit" for transformation products, a request is made to Metabolizer web services, then CTS walks through that result and renames keys to ones the frontend plotting library need. This is when the output page shows up and the products all have spinning wheels. This is where CTS backend goes through the list of products and obtains chemical information.

The chemical information process is the same as on the Chemical Editor. It runs the following filters in order:

    1. Removes explicit H, and then transform -- this is run in the same request, and a list of smiles is 
        returned, where the last one is chosen as the filtered smiles.

    2. Get major tautomer -- the filtered smiles from previous filtering is used to request the major 
        tautomer from jchem web services.

    3. Neutralize -- the result from step 2. is then used for the final filtering step: neutralize.

The local change I was talking about to fix the "hang up" was to add a check to step 2. If the tautomer request returns an error, it just uses the filtered smiles from step 1 and goes onto step 3.

**Comment by cstevens227** [comment]
This is not really a SMILES filtering issue.  It is a problem with one of the schemes (OxidativeDehalogentation) in the metabolism library.  This scheme produces an invalid structure in both the Metabolizer desktop application and CTS.  Unfortunately, we don't have access to the mammalian metabolism library to edit it. 
One way to fix the problem would be to remove explicit hydrogens from the bad structures.  I tried to do this with Standardizer, but it won't do anything with invalid structures.

**Comment by cstevens227** [comment]
I was able to fix the problem in the Metabolizer desktop application by adding an "Exclude Condition" under the Settings dropdown menu.  The Exclude Condition that I used was hasValenceError().  
I looked in the JChem API documentation, and there is a setExcludeCondition method.  Try something like:
metabolizer.setExcludeCondition(hasValenceError());
There is no harm in including this exclude condition for all libraries, because we don't want to be generating invalid structures.

**Comment by popenc** [comment]
@cstevens227 thanks, Caroline!

I need to clear up where this update should go exactly. CTS makes a request to metabolizer web services from CTSWS and not jchem web services directly.

Is this something that needs changing on the Metabolizer web service side? As in, the CTSWS stuff Kurt has built for us?

**Comment by cstevens227** [comment]
@popenc  Yes, I think we need to ask Kurt to fix it on CTSWS.

**Comment by popenc** [comment]
@kurtw555 Hey Kurt, I'm adding you on here as a participant on here. It looks like you're the hero we need (see Caroline's comments above).

**Comment by kurtw555** [comment]
The metabolizer API does have an argument for excludeconditon.  We could
try that.

**Comment by popenc** [comment]
I think this has been fixed now, right? Feel free to reopen if not.

**Comment by koopmans-michaela** [comment]
I tried to test this but I'm just getting spinning circles so I'm not sure if the exclude condition has been added/is working yet. From the SMILES I could see, it didn't look like it was.

**Comment by popenc** [comment]
Can you explain what you mean by spinning circles?

**Comment by koopmans-michaela** [comment]
I get the loading circles and the tree never ends up loading. However, the SMILES on that last product looks invalid so I'm thinking that the exclude condition either hasn't been set or isn't working.

![image](https://user-images.githubusercontent.com/26609201/32741725-3babc00e-c875-11e7-9d2b-338a3dba169e.png)

**Comment by popenc** [comment]
Alrighty thanks for the quick response! Wasn't aware that chemical info wasn't coming back in transformation workflow...

**Comment by koopmans-michaela** [comment]
It's coming back for other chemicals, I think it's just chemicals with this particular issue that aren't loading.

**Comment by popenc** [comment]
Whew, well that makes me feel a little better hah.

Last week I added some code on the CTS backend to skip the major tautomer step if an error is returned, which is what was happening with some of hexachloroethane's progeny. I just checked the QED master branch and realize this update isn't on the server, which explains why this isn't happen when I test this locally.

My comment from 6 days ago with the filtering steps does more into detail about that. I wasn't sure if the major tautomer skipping was something we wanted integrated into CTS so I've left it out of the server for now. Let me know what y'all think.

**Comment by koopmans-michaela** [comment]
Yeah, I think for now implementing the exclude condition will prevent any issues with getting the major tautomer, so we probably don't have to have code to skip that step. So long as we get the exclude condition working, it should weed out any chemicals that give you that major tautomer issue.
