### ISSUE TITLE
SMILES filter workflow check

### ISSUE THREAD

**Issue by popenc** [quanted/cts_app#98]
Need to provide raw JSON and logging of CTS backend for the SMILES filter workflow. For example, nicotine still has "@", "[ ]", and some explicit hydrogens.

**Comment by popenc** [comment]
Turns out, CTS backend was using the 'smiles' value from ACTORWS results as the standardized smiles in the Chemical Editor tab.

Locally, I've changed this to use ACTORWS SMILES as the original SMILES, but only if the user enters a chemical in a format that is not SMILES.

ACTORWS SMILES for nicotine: CN1CCC[C@H]1C1=CN=CC=C1

**Comment by popenc** [comment]
Making this a separate comment for organizational purposes, as this could turn into a related issue or something..

With the above change, that means the CTS Standardizer has an input SMILES of CN1CCC[C@H]1C1=CN=CC=C1.

Something that's confusing me is that the standardized SMILES coming out of CTS is still CN1CCC[C@H]1C1=CN=CC=C1 even with this change.



**Here's the order of events CTS performs for the SMILES standardization:**

1. CN1CCC[C@H]1C1=CN=CC=C1 is first removed of explicit hydrogens, then transformed. These two actions are performed in the same request and return two SMILES, both the same as the initial SMILES. CTS selects the last item in the list.

2. Next, CTS takes the selected SMILES from 1, and gets the major tautomer from jchem. For this example, the same SMILES is returned.

3. Lastly, CTS uses the SMILES returned from 2 and performs the "neutralize" filter. Once again, the same SMILES as before is returned and CTS uses this as the final filtered SMILES.

**Comment by cstevens227** [comment]
Before doing physicochemical property calculations, the SMILES strings need to be processed one more time.  In this final step, Standardizer should be used to "Clear Stereo" and transform "[N+](=O)[O-] → N(=O)=O" (which is the reverse of what is done in Step 1).  
The "Clear Stereo" standardization step should get rid of the @H in the example molecule CN1CCC[C@H]1C1=CN=CC=C1.

**Comment by popenc** [comment]
Good point. I forgot to add that the filtering steps I was mentioning were only at the Chemical Editor step and not the workflow for physicochemical requests.

I checked out the standardization used for physicochemical requests, and they seem to match with what you're describing, albeit it's currently calculator dependent.

Here's the current CTS standardization workflow for making a physicochemical request:

1. If the calculator is not chemaxon, perform a mass check and raise an error if chemical is greater than 1500 g/mol

2. If calculator is EPI, Measured, or SPARC, clear the stereoisomers and "untransform."

3. If calculator is EPI or Measured, check for any '[' or ']' in SMILES after above filtering, and raise an exception if they exist.

**Comment by popenc** [comment]
@cstevens227 @koopmans-michaela, Is this issue considered closed now?

The Standardized SMILES in the Chemical Editor tab should be correct now and not the ACTORWS one, which is what seemed to be the issue before. For the Initial SMILES, the ACTORWS  is used if the user enters a chemical not in the SMILES format, and if it is then the user's chemical is used as the Initial SMILES.

**Comment by koopmans-michaela** [comment]
Yep, I'm going through and verifying a bunch of fixes and this one looks good!
