### ISSUE TITLE
Incorrect pathway names in transformation products tree

### ISSUE THREAD

**Issue by popenc** [quanted/cts_app#99]
Transformation products reaction pathways aren't always correct. With an example chemical, document the raw JSON pre and post CTS to look at the "routes" list and which ones CTS selects to display.

**Comment by popenc** [comment]
@koopmans-michaela @cstevens227 

I was wondering if y'all had a good example chemical(s) would be that has incorrect pathways?

**Comment by koopmans-michaela** [comment]
One example that I had looked at before was pentachloroethane with the reduction library. Several pathways are incorrect in the tree, but the easiest to spot are shown below. Products 1.2.1 (first image) and 1.1.3 (second image) both say Hydrogenolysis for their individual pathway steps, but they should be Vicinal Dehalogenation. So their full pathways would be: Hydrogenolysis, Vicinal Dehalogenation. Does that make sense?

![pentachloroethane-pathwaynames1](https://user-images.githubusercontent.com/26609201/32741245-8acb6b82-c873-11e7-82a7-bd6f399fa6dd.PNG)

![pentachloroethane-pathwaynames2](https://user-images.githubusercontent.com/26609201/32741246-8add327c-c873-11e7-940b-d9997d2e170b.PNG)

**Comment by popenc** [comment]
OK, so I was able to get the pre-CTS JSON from the above transformation products request, and it definitely seems to reveal what's going on. Unless there's some blackbox chemistry I'm not accounting for, it looks like CTS should be grabbing the last item in the "route" list, not "routes."

I'll email y'all the JSON since it's pretty large.

**Comment by popenc** [comment]
This should be up on the server now. I'll wait to close it after y'all verify it though.

**Comment by koopmans-michaela** [comment]
Looks like it's working!
